repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: isort
        types: [python]

      - id: yapf
        name: yapf
        stages: [commit]
        language: system
        entry: yapf
        types: [python]
        args: ['--style=.style.yapf', '--parallel', '--in-place', '--recursive']

      - id: flake8
        name: flake8
        stages: [commit]
        language: system
        entry: flake8
        types: [python]

      - id: mypy
        name: mypy 
        stages: [commit]
        language: system
        entry: mypy
        types: [python]